services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DBNAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pvz-db"]
      interval: 10s
      retries: 5
    ports:
      - "5433:5432"

  goose:
    build:
      context: .
      dockerfile: build/goose/Dockerfile
    container_name: goose
    restart: no
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - GOOSE_DRIVER=${GOOSE_DRIVER}
      - GOOSE_DBSTRING=host=postgres port=5432 user=${PG_USER} password=${PG_PASSWORD} dbname=${PG_DBNAME} sslmode=${PG_SSL_MODE}
      - GOOSE_VERBOSE=true
    command: ["up"]
    volumes:
      - ./migrations:/migrations

  pvz:
    build:
      context: .
      dockerfile: build/pvz_app/Dockerfile
    container_name: pvz
    ports:
      - "16700:16700"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db_data:
