services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pvz-db
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pvz-db"]
      interval: 10s
      retries: 5

  pvz:
    build: .
    container_name: pvz
    ports:
      - "16700:16700"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
