// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authmocks

import (
	"github.com/shrtyk/avito-pvz-test-assignment/internal/core/domain/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokensService creates a new instance of MockTokensService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokensService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokensService {
	mock := &MockTokensService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokensService is an autogenerated mock type for the TokensService type
type MockTokensService struct {
	mock.Mock
}

type MockTokensService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokensService) EXPECT() *MockTokensService_Expecter {
	return &MockTokensService_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type MockTokensService
func (_mock *MockTokensService) GenerateAccessToken(tokenData auth.AccessTokenData) (string, error) {
	ret := _mock.Called(tokenData)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(auth.AccessTokenData) (string, error)); ok {
		return returnFunc(tokenData)
	}
	if returnFunc, ok := ret.Get(0).(func(auth.AccessTokenData) string); ok {
		r0 = returnFunc(tokenData)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(auth.AccessTokenData) error); ok {
		r1 = returnFunc(tokenData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokensService_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockTokensService_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - tokenData auth.AccessTokenData
func (_e *MockTokensService_Expecter) GenerateAccessToken(tokenData interface{}) *MockTokensService_GenerateAccessToken_Call {
	return &MockTokensService_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", tokenData)}
}

func (_c *MockTokensService_GenerateAccessToken_Call) Run(run func(tokenData auth.AccessTokenData)) *MockTokensService_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 auth.AccessTokenData
		if args[0] != nil {
			arg0 = args[0].(auth.AccessTokenData)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokensService_GenerateAccessToken_Call) Return(s string, err error) *MockTokensService_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokensService_GenerateAccessToken_Call) RunAndReturn(run func(tokenData auth.AccessTokenData) (string, error)) *MockTokensService_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenClaims provides a mock function for the type MockTokensService
func (_mock *MockTokensService) GetTokenClaims(token string) (*auth.AccessTokenClaims, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenClaims")
	}

	var r0 *auth.AccessTokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*auth.AccessTokenClaims, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *auth.AccessTokenClaims); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AccessTokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokensService_GetTokenClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenClaims'
type MockTokensService_GetTokenClaims_Call struct {
	*mock.Call
}

// GetTokenClaims is a helper method to define mock.On call
//   - token string
func (_e *MockTokensService_Expecter) GetTokenClaims(token interface{}) *MockTokensService_GetTokenClaims_Call {
	return &MockTokensService_GetTokenClaims_Call{Call: _e.mock.On("GetTokenClaims", token)}
}

func (_c *MockTokensService_GetTokenClaims_Call) Run(run func(token string)) *MockTokensService_GetTokenClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokensService_GetTokenClaims_Call) Return(accessTokenClaims *auth.AccessTokenClaims, err error) *MockTokensService_GetTokenClaims_Call {
	_c.Call.Return(accessTokenClaims, err)
	return _c
}

func (_c *MockTokensService_GetTokenClaims_Call) RunAndReturn(run func(token string) (*auth.AccessTokenClaims, error)) *MockTokensService_GetTokenClaims_Call {
	_c.Call.Return(run)
	return _c
}
