// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package authmocks

import (
	"github.com/shrtyk/avito-pvz-test-assignment/internal/core/domain/auth"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTokenService creates a new instance of MockTokenService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenService {
	mock := &MockTokenService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTokenService is an autogenerated mock type for the TokenService type
type MockTokenService struct {
	mock.Mock
}

type MockTokenService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenService) EXPECT() *MockTokenService_Expecter {
	return &MockTokenService_Expecter{mock: &_m.Mock}
}

// Fingerprint provides a mock function for the type MockTokenService
func (_mock *MockTokenService) Fingerprint(rToken *auth.RefreshToken) string {
	ret := _mock.Called(rToken)

	if len(ret) == 0 {
		panic("no return value specified for Fingerprint")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(*auth.RefreshToken) string); ok {
		r0 = returnFunc(rToken)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockTokenService_Fingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fingerprint'
type MockTokenService_Fingerprint_Call struct {
	*mock.Call
}

// Fingerprint is a helper method to define mock.On call
//   - rToken *auth.RefreshToken
func (_e *MockTokenService_Expecter) Fingerprint(rToken interface{}) *MockTokenService_Fingerprint_Call {
	return &MockTokenService_Fingerprint_Call{Call: _e.mock.On("Fingerprint", rToken)}
}

func (_c *MockTokenService_Fingerprint_Call) Run(run func(rToken *auth.RefreshToken)) *MockTokenService_Fingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *auth.RefreshToken
		if args[0] != nil {
			arg0 = args[0].(*auth.RefreshToken)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_Fingerprint_Call) Return(s string) *MockTokenService_Fingerprint_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockTokenService_Fingerprint_Call) RunAndReturn(run func(rToken *auth.RefreshToken) string) *MockTokenService_Fingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateAccessToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GenerateAccessToken(tokenData auth.AccessTokenData) (string, error) {
	ret := _mock.Called(tokenData)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(auth.AccessTokenData) (string, error)); ok {
		return returnFunc(tokenData)
	}
	if returnFunc, ok := ret.Get(0).(func(auth.AccessTokenData) string); ok {
		r0 = returnFunc(tokenData)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(auth.AccessTokenData) error); ok {
		r1 = returnFunc(tokenData)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type MockTokenService_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - tokenData auth.AccessTokenData
func (_e *MockTokenService_Expecter) GenerateAccessToken(tokenData interface{}) *MockTokenService_GenerateAccessToken_Call {
	return &MockTokenService_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", tokenData)}
}

func (_c *MockTokenService_GenerateAccessToken_Call) Run(run func(tokenData auth.AccessTokenData)) *MockTokenService_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 auth.AccessTokenData
		if args[0] != nil {
			arg0 = args[0].(auth.AccessTokenData)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_GenerateAccessToken_Call) Return(s string, err error) *MockTokenService_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockTokenService_GenerateAccessToken_Call) RunAndReturn(run func(tokenData auth.AccessTokenData) (string, error)) *MockTokenService_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// GenerateRefreshToken provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GenerateRefreshToken(userID string, ua string, ip string) *auth.RefreshToken {
	ret := _mock.Called(userID, ua, ip)

	if len(ret) == 0 {
		panic("no return value specified for GenerateRefreshToken")
	}

	var r0 *auth.RefreshToken
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *auth.RefreshToken); ok {
		r0 = returnFunc(userID, ua, ip)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RefreshToken)
		}
	}
	return r0
}

// MockTokenService_GenerateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateRefreshToken'
type MockTokenService_GenerateRefreshToken_Call struct {
	*mock.Call
}

// GenerateRefreshToken is a helper method to define mock.On call
//   - userID string
//   - ua string
//   - ip string
func (_e *MockTokenService_Expecter) GenerateRefreshToken(userID interface{}, ua interface{}, ip interface{}) *MockTokenService_GenerateRefreshToken_Call {
	return &MockTokenService_GenerateRefreshToken_Call{Call: _e.mock.On("GenerateRefreshToken", userID, ua, ip)}
}

func (_c *MockTokenService_GenerateRefreshToken_Call) Run(run func(userID string, ua string, ip string)) *MockTokenService_GenerateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTokenService_GenerateRefreshToken_Call) Return(refreshToken *auth.RefreshToken) *MockTokenService_GenerateRefreshToken_Call {
	_c.Call.Return(refreshToken)
	return _c
}

func (_c *MockTokenService_GenerateRefreshToken_Call) RunAndReturn(run func(userID string, ua string, ip string) *auth.RefreshToken) *MockTokenService_GenerateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// GetTokenClaims provides a mock function for the type MockTokenService
func (_mock *MockTokenService) GetTokenClaims(token string) (*auth.AccessTokenClaims, error) {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for GetTokenClaims")
	}

	var r0 *auth.AccessTokenClaims
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*auth.AccessTokenClaims, error)); ok {
		return returnFunc(token)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *auth.AccessTokenClaims); ok {
		r0 = returnFunc(token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AccessTokenClaims)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTokenService_GetTokenClaims_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTokenClaims'
type MockTokenService_GetTokenClaims_Call struct {
	*mock.Call
}

// GetTokenClaims is a helper method to define mock.On call
//   - token string
func (_e *MockTokenService_Expecter) GetTokenClaims(token interface{}) *MockTokenService_GetTokenClaims_Call {
	return &MockTokenService_GetTokenClaims_Call{Call: _e.mock.On("GetTokenClaims", token)}
}

func (_c *MockTokenService_GetTokenClaims_Call) Run(run func(token string)) *MockTokenService_GetTokenClaims_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockTokenService_GetTokenClaims_Call) Return(accessTokenClaims *auth.AccessTokenClaims, err error) *MockTokenService_GetTokenClaims_Call {
	_c.Call.Return(accessTokenClaims, err)
	return _c
}

func (_c *MockTokenService_GetTokenClaims_Call) RunAndReturn(run func(token string) (*auth.AccessTokenClaims, error)) *MockTokenService_GetTokenClaims_Call {
	_c.Call.Return(run)
	return _c
}
